//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobDetailsDynamicField
    {
        public int ID { get; set; }
        public Nullable<int> JobDetailsID { get; set; }
        public Nullable<int> DynamicFieldID { get; set; }
        public string Anwer { get; set; }
    
        public virtual Vt_DynamicFields Vt_DynamicFields { get; set; }
        public virtual Vt_JobDetails Vt_JobDetails { get; set; }
    }
}
