//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vt_DynamicFieldsValues
    {
        public int ID { get; set; }
        public Nullable<int> DynamicFieldsID { get; set; }
        public string FieldText { get; set; }
        public string FieldValue { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Vt_DynamicFields Vt_DynamicFields { get; set; }
    }
}
