//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vt_JobDrafting_Drafter_Questions
    {
        public int ID { get; set; }
        public Nullable<int> DrafterQuestionID { get; set; }
        public string Heading { get; set; }
        public string DrafterQuestion { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
