//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vt_JobEstimationDetails
    {
        public int ID { get; set; }
        public int JobEstimationID { get; set; }
        public int JobID { get; set; }
        public Nullable<int> StageID { get; set; }
        public int ProductID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public int MarkupValue { get; set; }
        public string Notes { get; set; }
    
        public virtual Vt_JobEstimation Vt_JobEstimation { get; set; }
        public virtual Vt_Products Vt_Products { get; set; }
        public virtual Vt_Jobs Vt_Jobs { get; set; }
    }
}
