//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vt_JobDrafting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vt_JobDrafting()
        {
            this.Vt_JobDrafting_Drafter_Checklist = new HashSet<Vt_JobDrafting_Drafter_Checklist>();
            this.Vt_JobDrafting_Checker_Checklist = new HashSet<Vt_JobDrafting_Checker_Checklist>();
        }
    
        public int ID { get; set; }
        public int JobID { get; set; }
        public string JobNo { get; set; }
        public Nullable<int> DrafterID { get; set; }
        public Nullable<int> CheckerID { get; set; }
        public Nullable<System.DateTime> DraftingDueDate { get; set; }
        public Nullable<System.DateTime> CheckerDueDate { get; set; }
        public Nullable<System.DateTime> DraftingCompletionDate { get; set; }
        public Nullable<System.DateTime> CheckerCompletionDate { get; set; }
        public Nullable<System.DateTime> EngineeringCompletionDate { get; set; }
        public Nullable<System.DateTime> BookletSentDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vt_JobDrafting_Drafter_Checklist> Vt_JobDrafting_Drafter_Checklist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vt_JobDrafting_Checker_Checklist> Vt_JobDrafting_Checker_Checklist { get; set; }
        public virtual Vt_Jobs Vt_Jobs { get; set; }
    }
}
