//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vt_Jobs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vt_Jobs()
        {
            this.Vt_JobDetails = new HashSet<Vt_JobDetails>();
            this.Vt_JobDrafting = new HashSet<Vt_JobDrafting>();
            this.Vt_JobEstimation = new HashSet<Vt_JobEstimation>();
            this.Vt_JobEstimationDetails = new HashSet<Vt_JobEstimationDetails>();
            this.Vt_ManufacturingOrderDetails = new HashSet<Vt_ManufacturingOrderDetails>();
        }
    
        public int ID { get; set; }
        public string JobNo { get; set; }
        public string JobTitle { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Owner { get; set; }
        public string SiteAddress { get; set; }
        public string SiteContactName { get; set; }
        public string SiteContactPhoneNumber { get; set; }
        public string OfficeContactName { get; set; }
        public string OfficeContactPhoneNumber { get; set; }
        public Nullable<int> AssignedTo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vt_JobDetails> Vt_JobDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vt_JobDrafting> Vt_JobDrafting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vt_JobEstimation> Vt_JobEstimation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vt_JobEstimationDetails> Vt_JobEstimationDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vt_ManufacturingOrderDetails> Vt_ManufacturingOrderDetails { get; set; }
    }
}
