//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vt_JobEstimation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vt_JobEstimation()
        {
            this.Vt_JobEstimationDetails = new HashSet<Vt_JobEstimationDetails>();
        }
    
        public int ID { get; set; }
        public int JobID { get; set; }
        public int CustomerID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string QuoteNumber { get; set; }
        public string RevisionNumber { get; set; }
        public Nullable<int> MarkupValue { get; set; }
    
        public virtual Vt_Customers Vt_Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vt_JobEstimationDetails> Vt_JobEstimationDetails { get; set; }
        public virtual Vt_Jobs Vt_Jobs { get; set; }
    }
}
